# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
    
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js, NPM and Yarn
      uses: actions/setup-node@v1
      with:
          node-version: 16
    - name: install package
      run: npm install
    - name: install child
      run: npm run install-child
    - name: lerna bootstrap
      run: npm run lerna
    - name: make pkg
      run: npm run pkg
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # need this for all history for all branches and tags
    - name: Create Release
      id: create_release
      uses: nickatnight/releases-action@v3
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      ReleaseTag: ${{ steps.create_release.outputs.release_tag }}
